name: Post Lyrics

on:
  schedule:
    - cron: '0 0 * * *'   # 00:00 UTC
    - cron: '0 6 * * *'   # 06:00 UTC
    - cron: '0 12 * * *'  # 12:00 UTC
    - cron: '0 18 * * *'  # 18:00 UTC
  workflow_dispatch:       # allows manual trigger

jobs:
  post_lyric:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install tweepy

      - name: Run bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        run: python bot.py
